version: "3"

services:
  openresty:
    build:
      context: .
      dockerfile: ./compose/openresty/Dockerfile
    volumes:
      - ./logs/nginx:/var/log/nginx
    ports:
    - 80:80

  web:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    restart: always
    env_file:
      - ./web/.env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend/files:/app/files
      - ./backend/data/static:/app/data/static
      - ./logs/backend:/app/logs
      - ./backend/cmdb/migrations:/app/web/app/migrations
    command: /start

  celery:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
      - web
    command: /start-celeryworker

  beat:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
      - web
    command: /start-celerybeat


  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - /data/postgresql/backups:/backups
    env_file:
      - ./backend/.env

  redis:
    image: redis:5.0

networks:
  default:
    external:
      name: ops
