# Generated by Django 5.2.15 on 2026-06-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_accesskey_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginlog',
            name='reason',
            field=models.SmallIntegerField(choices=[(0, '-'), (1, '用戶名/密碼 校驗失敗'), (2, 'MFA authentication failed'), (3, '用戶名不存在'), (4, '密碼已過期')], default=0, verbose_name='Reason'),
        ),
    ]
