# Generated by Django 5.2.15 on 2026-06-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.IntegerField(default=0, verbose_name='操作人ID')),
                ('action', models.CharField(max_length=50, verbose_name='操作類型')),
                ('resource_type', models.CharField(max_length=100, verbose_name='資源類型')),
                ('resource_id', models.CharField(max_length=255, verbose_name='資源ID')),
                ('resource_name', models.CharField(default='', max_length=255, verbose_name='資源名稱')),
                ('old_values', models.TextField(default='{}', verbose_name='舊值')),
                ('new_values', models.TextField(default='{}', verbose_name='新值')),
                ('reason', models.CharField(default='', max_length=255, verbose_name='原因')),
                ('ip', models.GenericIPAddressField(default='', verbose_name='IP')),
                ('user_agent', models.CharField(default='', max_length=255, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '操作審計日誌',
                'verbose_name_plural': '操作審計日誌',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, unique=True, verbose_name='角色名稱')),
                ('menus', models.TextField(default='[]', verbose_name='菜單權限')),
                ('actions', models.TextField(default='[]', verbose_name='動作權限')),
            ],
            options={
                'verbose_name': '角色權限分配表',
                'verbose_name_plural': '角色權限分配表',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', '管理員'), ('operator', '運維工程師'), ('auditor', '安全審計員'), ('visitor', '訪客')], default='visitor', max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
