#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# N.B. If only .env files supported variable expansion...
export CELERY_BROKER_URL="${REDIS_URL}"

db_ready() {
python << END
import sys
import socket

try:
    s = socket.create_connection(("${DB_HOST}", int("${DB_PORT}")), timeout=2)
    s.close()
except Exception:
    sys.exit(-1)
sys.exit(0)
END
}

until db_ready; do
  >&2 echo "Waiting for Database (${DB_HOST}:${DB_PORT}) to become available..."
  sleep 1
done
>&2 echo "Database is available"

exec "$@"
