# Generated by Django 2.1.4 on 2020-11-19 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hosts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_celery_beat', '0011_auto_20190508_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='業務線')),
                ('enname', models.CharField(max_length=64, verbose_name='英文')),
                ('remark', models.TextField(blank=True, verbose_name='備註')),
            ],
            options={
                'verbose_name_plural': '業務線表',
            },
        ),
        migrations.CreateModel(
            name='CmdRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_as', models.CharField(default='root', max_length=64, verbose_name='運行用戶')),
                ('command', models.TextField(verbose_name='Command')),
                ('_result', models.TextField(blank=True, null=True, verbose_name='Result')),
                ('is_finished', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_start', models.DateTimeField(null=True)),
                ('date_finished', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=64, verbose_name='插槽位置')),
                ('manufacturer', models.CharField(blank=True, max_length=64, verbose_name='製造商')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='型號')),
                ('cores', models.SmallIntegerField(blank=True, verbose_name='cores')),
                ('threads', models.SmallIntegerField(blank=True, null=True, verbose_name='threads')),
            ],
            options={
                'verbose_name_plural': 'CPU表',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=64, verbose_name='插槽位置')),
                ('model', models.CharField(blank=True, max_length=64, null=True, verbose_name='硬盤型號')),
                ('capacity', models.FloatField(blank=True, null=True, verbose_name='硬盤容量')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='硬碟序號')),
                ('manufacturer', models.CharField(blank=True, max_length=32, null=True, verbose_name='製造商')),
                ('iface_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='接口類型')),
            ],
            options={
                'verbose_name_plural': '硬盤表',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate', models.SmallIntegerField(choices=[(1, '服務器'), (2, '虛擬機')], default=1, verbose_name='類型')),
                ('name', models.CharField(max_length=64, verbose_name='主機名稱')),
                ('sn', models.CharField(max_length=64, verbose_name='SN序號')),
                ('manufacturer', models.CharField(blank=True, max_length=64, verbose_name='製造商')),
                ('model', models.CharField(blank=True, max_length=64, null=True, verbose_name='型號')),
                ('manage_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('os_distribution', models.CharField(blank=True, max_length=64, verbose_name='發行版本')),
                ('os_platform', models.CharField(blank=True, max_length=64, verbose_name='系統')),
                ('os_version', models.CharField(blank=True, max_length=64, verbose_name='系統版本')),
                ('latest_date', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(choices=[(True, '啟用'), (False, '未啟用')], default=False, verbose_name='啟用狀態')),
                ('total_cores', models.PositiveIntegerField(blank=True, null=True)),
                ('total_disk', models.PositiveIntegerField(blank=True, null=True)),
                ('total_memory', models.PositiveIntegerField(blank=True, null=True)),
                ('manage_ssh', models.CharField(default='22', max_length=16, verbose_name='sshd')),
                ('bus_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.BusinessUnit', verbose_name='業務線')),
            ],
            options={
                'verbose_name': '服務器',
                'verbose_name_plural': '服務器表',
                'ordering': ['-latest_date'],
            },
        ),
        migrations.CreateModel(
            name='HostNet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HostNet', to='hosts.Host')),
            ],
            options={
                'verbose_name': '服務器網路端口表',
                'verbose_name_plural': '服務器網路端口表',
            },
        ),
        migrations.CreateModel(
            name='HostProc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HostProc', to='hosts.Host')),
            ],
            options={
                'verbose_name': '服務器進程表',
                'verbose_name_plural': '服務器進程表',
            },
        ),
        migrations.CreateModel(
            name='HostRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='創建日期')),
                ('host_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostrecord', to='hosts.Host')),
            ],
            options={
                'verbose_name_plural': '主機紀錄表',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='IDRAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idrac_ip', models.GenericIPAddressField(verbose_name='IDRAC IP')),
                ('port', models.PositiveSmallIntegerField(default=443, verbose_name='端口')),
                ('host', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.Host', verbose_name='Host')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.PeriodicTask', verbose_name='任務')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=64, verbose_name='插槽位置')),
                ('manufacturer', models.CharField(blank=True, max_length=32, null=True, verbose_name='製造商')),
                ('model', models.CharField(max_length=64, verbose_name='型號')),
                ('capacity', models.FloatField(blank=True, null=True, verbose_name='內存容量')),
                ('sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='內存SN號')),
                ('host_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='hosts.Host')),
            ],
            options={
                'verbose_name_plural': '内存表',
            },
        ),
        migrations.CreateModel(
            name='Net',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proto', models.CharField(max_length=64)),
                ('port', models.CharField(max_length=64)),
                ('pid', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='NIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='網卡名稱')),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='型號')),
                ('macaddress', models.CharField(blank=True, max_length=255, null=True, verbose_name='MAC')),
                ('netmask', models.CharField(blank=True, max_length=255, null=True, verbose_name='Netmask')),
                ('host_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nic', to='hosts.Host')),
            ],
            options={
                'verbose_name_plural': '網卡表',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='進程名稱')),
                ('status', models.CharField(max_length=255, verbose_name='狀態')),
                ('username', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField()),
                ('pid', models.IntegerField()),
                ('cmdline', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '進程表',
                'verbose_name_plural': '進程表',
            },
        ),
        migrations.CreateModel(
            name='RunUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名稱')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='用戶名')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='密鑰')),
                ('private_key', models.FileField(blank=True, null=True, upload_to=hosts.models.content_file_name, verbose_name='私鑰')),
                ('comment', models.TextField(blank=True, verbose_name='備註')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='創建日期')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('created_by', models.CharField(max_length=128, null=True, verbose_name='Created by')),
            ],
            options={
                'verbose_name': '執行用戶',
                'verbose_name_plural': '執行用戶',
            },
        ),
        migrations.AddField(
            model_name='hostproc',
            name='proc',
            field=models.ManyToManyField(to='hosts.Process'),
        ),
        migrations.AddField(
            model_name='hostnet',
            name='net',
            field=models.ManyToManyField(to='hosts.Net'),
        ),
        migrations.AddField(
            model_name='host',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.Node', verbose_name='分支'),
        ),
        migrations.AddField(
            model_name='disk',
            name='host_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk', to='hosts.Host'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='host_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpu', to='hosts.Host'),
        ),
        migrations.AddField(
            model_name='cmdrecord',
            name='host',
            field=models.ManyToManyField(to='hosts.Host', verbose_name='主機'),
        ),
        migrations.AddField(
            model_name='cmdrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用戶'),
        ),
    ]
