# Generated by Django 5.2.15 on 2026-06-28 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostnet',
            options={'verbose_name': '服務器網路埠表', 'verbose_name_plural': '服務器網路埠表'},
        ),
        migrations.AlterModelOptions(
            name='memory',
            options={'verbose_name_plural': '內存表'},
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cmdrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='host',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hostnet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hostproc',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hostrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='idrac',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='idrac',
            name='port',
            field=models.PositiveSmallIntegerField(default=443, verbose_name='埠'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='net',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='process',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='runuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='BIOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(default='', max_length=64, verbose_name='製造商')),
                ('version', models.CharField(default='', max_length=64, verbose_name='版本')),
                ('release_date', models.CharField(default='', max_length=20, verbose_name='發布日期')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('host_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bios', to='hosts.host')),
            ],
            options={
                'verbose_name': 'BIOS',
                'verbose_name_plural': 'BIOS',
            },
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='名稱')),
                ('model', models.CharField(default='', max_length=255, verbose_name='型號')),
                ('key', models.CharField(default='', max_length=255, verbose_name='Key')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controller', to='hosts.host')),
            ],
            options={
                'verbose_name': 'Controller',
                'verbose_name_plural': 'Controller',
            },
        ),
        migrations.CreateModel(
            name='ControllerBattery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='名稱')),
                ('model', models.CharField(default='', max_length=255, verbose_name='型號')),
                ('key', models.CharField(default='', max_length=255, verbose_name='Key')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controllerbattery', to='hosts.host')),
            ],
            options={
                'verbose_name': 'ControllerBattery',
                'verbose_name_plural': 'ControllerBattery',
            },
        ),
        migrations.CreateModel(
            name='ControllerSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='名稱')),
                ('status', models.CharField(default='', max_length=64, verbose_name='狀態')),
                ('key', models.CharField(default='', max_length=255, verbose_name='Key')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controllersensor', to='hosts.host')),
            ],
            options={
                'verbose_name': 'ControllerSensor',
                'verbose_name_plural': 'ControllerSensor',
            },
        ),
        migrations.CreateModel(
            name='Enclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='名稱')),
                ('model', models.CharField(default='', max_length=255, verbose_name='型號')),
                ('key', models.CharField(default='', max_length=255, verbose_name='Key')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enclosure', to='hosts.host')),
            ],
            options={
                'verbose_name': 'Enclosure',
                'verbose_name_plural': 'Enclosure',
            },
        ),
        migrations.CreateModel(
            name='EnclosureSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='名稱')),
                ('status', models.CharField(default='', max_length=64, verbose_name='狀態')),
                ('key', models.CharField(default='', max_length=255, verbose_name='Key')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enclosuresensor', to='hosts.host')),
            ],
            options={
                'verbose_name': 'EnclosureSensor',
                'verbose_name_plural': 'EnclosureSensor',
            },
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='名稱')),
                ('status', models.CharField(default='', max_length=64, verbose_name='狀態')),
                ('key', models.CharField(default='', max_length=255, verbose_name='Key')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fan', to='hosts.host')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fan',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='名稱')),
                ('edition', models.CharField(default='', max_length=255, verbose_name='版本')),
                ('key', models.CharField(default='', max_length=255, verbose_name='Key')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license', to='hosts.host')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'License',
            },
        ),
        migrations.CreateModel(
            name='PCIDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='名稱')),
                ('vendor', models.CharField(default='', max_length=255, verbose_name='廠商')),
                ('device_id', models.CharField(default='', max_length=64, verbose_name='Device ID')),
                ('key', models.CharField(default='', max_length=255, verbose_name='Key')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcidevice', to='hosts.host')),
            ],
            options={
                'verbose_name': 'PCIDevice',
                'verbose_name_plural': 'PCIDevice',
            },
        ),
        migrations.CreateModel(
            name='PhysicalDisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='名稱')),
                ('model', models.CharField(default='', max_length=255, verbose_name='型號')),
                ('capacity', models.FloatField(blank=True, null=True, verbose_name='容量')),
                ('key', models.CharField(default='', max_length=255, verbose_name='Key')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physicaldisk', to='hosts.host')),
            ],
            options={
                'verbose_name': 'PhysicalDisk',
                'verbose_name_plural': 'PhysicalDisk',
            },
        ),
    ]
