# Generated by Django 2.1.4 on 2020-11-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名稱')),
                ('capacity', models.BigIntegerField(verbose_name='總容量')),
                ('freeSpace', models.BigIntegerField(verbose_name='可用空間')),
                ('provisioned', models.BigIntegerField(blank=True, verbose_name='置備的空間')),
                ('type', models.CharField(blank=True, max_length=255, verbose_name='文件系統')),
                ('status', models.BooleanField(default=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='別名')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_date', models.DateTimeField(auto_now=True)),
                ('ansible_all_ipv4_addresses', models.GenericIPAddressField()),
                ('ansible_processor', models.CharField(max_length=255)),
                ('ansible_processor_cores', models.PositiveIntegerField()),
                ('ansible_processor_count', models.PositiveIntegerField()),
                ('ansible_processor_vcpus', models.PositiveIntegerField()),
                ('ansible_memfree_mb', models.PositiveIntegerField()),
                ('ansible_memtotal_mb', models.PositiveIntegerField()),
                ('ansible_distribution', models.CharField(max_length=255)),
                ('ansible_distribution_version', models.CharField(max_length=255)),
                ('ansible_system_vendor', models.CharField(max_length=255)),
                ('ansible_product_name', models.CharField(max_length=255)),
                ('ansible_product_serial', models.CharField(max_length=255)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='vm.Cluster')),
                ('datastore', models.ManyToManyField(to='vm.DataStore')),
            ],
        ),
        migrations.CreateModel(
            name='HostRunTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date', models.DateTimeField(auto_now=True)),
                ('Host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vm.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hw_name', models.CharField(max_length=255)),
                ('hw_guest_full_name', models.CharField(blank=True, max_length=255)),
                ('hw_power_status', models.CharField(choices=[('poweredOn', '運行中'), ('poweredOff', '已停止'), ('building', '建置中')], max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=255)),
                ('instance_uuid', models.UUIDField(blank=True, null=True)),
                ('hw_processor_count', models.PositiveIntegerField(verbose_name='CPU')),
                ('hw_cores_per_socket', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cores')),
                ('hw_memtotal_mb', models.PositiveIntegerField(verbose_name='Memory')),
                ('capacity', models.PositiveIntegerField(verbose_name='capacity')),
                ('task', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('latest_date', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('hw_is_template', models.BooleanField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance', to='vm.Cluster')),
                ('datastore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vm.DataStore')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='vm.Host')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='NetWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('network', models.CharField(max_length=255)),
                ('vlan_id', models.CharField(max_length=255)),
                ('vswitch', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='別名')),
                ('dhcp', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetWorkStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('lan', models.CharField(max_length=255)),
                ('gateway', models.CharField(max_length=255)),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='別名')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vm.NetWork')),
                ('template', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vm.Instance')),
            ],
        ),
        migrations.CreateModel(
            name='RunTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_allocation_expandable_reservation', models.BooleanField()),
                ('cpu_allocation_limit', models.PositiveIntegerField()),
                ('cpu_allocation_overhead_limit', models.CharField(blank=True, max_length=255)),
                ('cpu_allocation_reservation', models.PositiveIntegerField()),
                ('cpu_allocation_shares', models.PositiveIntegerField()),
                ('cpu_allocation_shares_level', models.CharField(max_length=255)),
                ('mem_allocation_expandable_reservation', models.BooleanField()),
                ('mem_allocation_limit', models.PositiveIntegerField()),
                ('mem_allocation_overhead_limit', models.CharField(blank=True, max_length=255)),
                ('mem_allocation_reservation', models.PositiveIntegerField()),
                ('mem_allocation_shares', models.PositiveIntegerField()),
                ('mem_allocation_shares_level', models.CharField(blank=True, max_length=255)),
                ('runtime_cpu_max_usage', models.PositiveIntegerField()),
                ('runtime_cpu_overall_usage', models.PositiveIntegerField()),
                ('runtime_cpu_reservation_used', models.PositiveIntegerField()),
                ('runtime_cpu_reservation_used_vm', models.PositiveIntegerField()),
                ('runtime_cpu_unreserved_for_pool', models.PositiveIntegerField()),
                ('runtime_cpu_unreserved_for_vm', models.PositiveIntegerField()),
                ('runtime_memory_max_usage', models.PositiveIntegerField()),
                ('runtime_memory_overall_usage', models.PositiveIntegerField()),
                ('runtime_memory_reservation_used', models.PositiveIntegerField()),
                ('runtime_memory_reservation_used_vm', models.PositiveIntegerField()),
                ('runtime_memory_unreserved_for_pool', models.PositiveIntegerField()),
                ('runtime_memory_unreserved_for_vm', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'running'), (2, 'stop'), (3, 'restart'), (4, '正在初始化中'), (5, '構建失敗')], default=4)),
                ('check', models.CharField(default='', max_length=64)),
                ('task', models.CharField(default='', max_length=64)),
                ('is_finish', models.BooleanField(default=False)),
                ('manage_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('latest_date', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=255)),
                ('cpu', models.PositiveIntegerField()),
                ('memory', models.PositiveIntegerField()),
                ('disk_size', models.PositiveIntegerField()),
                ('instance', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vm.Instance')),
            ],
        ),
        migrations.AddField(
            model_name='instance',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vm.NetWork'),
        ),
        migrations.AddField(
            model_name='hostruntime',
            name='RunTime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vm.RunTime'),
        ),
        migrations.AddField(
            model_name='host',
            name='network',
            field=models.ManyToManyField(to='vm.NetWork'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='network',
            field=models.ManyToManyField(to='vm.NetWork'),
        ),
    ]
